// Code generated by protoc-gen-go-xorm. DO NOT EDIT!
// Power by lwj

package testpb

// base xorm.io/xorm/convert

// FromDB implements convert.Conversion
func (x *Status_Def) FromDB(b []byte) error {
	key := string(b)
	value, ok := Status_Def_value[key]
	if ok {
		*x = Status_Def(value)
	}
	return nil
}

// ToDB implements convert.Conversion
func (x *Status_Def) ToDB() ([]byte, error) {
	return []byte(x.String()), nil
}

// base xorm.io/xorm/convert

// FromDB implements convert.Conversion
func (x *Status1_Def) FromDB(b []byte) error {
	key := string(b)
	value, ok := Status1_Def_value[key]
	if ok {
		*x = Status1_Def(value)
	}
	return nil
}

// ToDB implements convert.Conversion
func (x *Status1_Def) ToDB() ([]byte, error) {
	return []byte(x.String()), nil
}

// base xorm.io/xorm/convert

// FromDB implements convert.Conversion
func (x *Status2_Def) FromDB(b []byte) error {
	key := string(b)
	value, ok := Status2_Def_value[key]
	if ok {
		*x = Status2_Def(value)
	}
	return nil
}

// ToDB implements convert.Conversion
func (x *Status2_Def) ToDB() ([]byte, error) {
	return []byte(x.String()), nil
}
